# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.FloatField()),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('count', models.IntegerField(default=10, verbose_name='Кол-во')),
                ('preview', models.TextField(blank=True, default='', null=True, verbose_name='Превью')),
                ('date_create', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('is_true', models.BooleanField(default=False, verbose_name='Это правда?')),
            ],
            options={
                'verbose_name': 'Урок 5',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
